# Generated by Django 5.0.6 on 2024-05-18 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(blank=True, max_length=4096)),
                ('lead', models.CharField(default='John Doe', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('text', models.TextField(blank=True, max_length=4096)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('video', models.FileField(blank=True, upload_to='')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='case.case')),
            ],
        ),
    ]
