# Generated by Django 5.0.6 on 2024-05-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='audio',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
