# Generated by Django 5.0.6 on 2024-05-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='lead',
            field=models.CharField(default='John Doe', max_length=512),
        ),
    ]
